### ISSUE TITLE
Integración de dataset latinoamérica

### ISSUE THREAD

**Issue by ZurMaD** [reactcostarica/coronaviruscr#17]
Hola, junto con una organización sin fines de lucro se está tratando de centralizar la información de contagiados/muertos/recuperados covid-19 y estamos buscando un encargado por país. En tu caso Costa Rica.

El formato del csv se está manejando acorde al formato global https://github.com/CSSEGISandData/COVID-19 para luego poder juntar la data.
Esto comprende las siguientes columnas:

![image](https://user-images.githubusercontent.com/28235457/77203603-cafb0380-6abe-11ea-93ed-0b62ccbc93f8.png)

Para Costa Rica se necesitaría actualización diaria para estos lugares:
![image](https://user-images.githubusercontent.com/28235457/77218647-86da2400-6afb-11ea-89c7-ca54f68806cc.png)

Podrías comentarme si estás interesado en aportar porfavor.
El dataset centralizado se propone en este repositorio: https://github.com/DataScienceResearchPeru/covid-19_pe

**Comment by kevinwolfdev** [comment]
¡Hola @ZurMaD! Nos encantaría colaborar. Actualmente tenemos un Slack en donde estamos conversando activamente sobre el tema de este repositorio. ¿Querés pasarme tu e-mail para invitarte?

**Comment by ZurMaD** [comment]
Gracias por tu interés, te dejo mi e-mail pablo.diazv@pucp.edu.pe

**Comment by kevinwolfdev** [comment]
Hola @ZurMaD. El dataset está disponible en https://coronaviruscr.com/api/reports

Saludos.

**Comment by ZurMaD** [comment]
Muchas gracias, excelente.
